### ISSUE TITLE
Hide labels and lines

### ISSUE THREAD

**Issue by philmodin** [misyobun/MSBBarChart#15]
We have a section where we would like to hide all elements except the bars.

Before
![IMG_8644](https://user-images.githubusercontent.com/18331871/84457092-a07c9a80-ac16-11ea-95a7-6767b33baad6.jpg)

After
![IMG_8643](https://user-images.githubusercontent.com/18331871/84457090-9f4b6d80-ac16-11ea-91c2-2a7c11111bcc.jpg)

Request to let us hide labels and axis lines please.

**Comment by misyobun** [comment]
@pvmodin 
like this?
![スクリーンショット 2020-06-12 18 21 09](https://user-images.githubusercontent.com/509448/84487306-8657c080-acd9-11ea-9d25-fcb80300c8e7.png)

**Comment by philmodin** [comment]
@misyobun That looks about right. Is the spacing even on both sides? Would be nice to have even margins on both sides even if the y axis value is high.

**Comment by misyobun** [comment]
@pvmodin 
Based on your request, I made same space(margin) of both sides.
And I think that bottom space seems unnecessary in this situation.
so, I remove bottom space.
It's like this.

![スクリーンショット 2020-06-12 18 55 08](https://user-images.githubusercontent.com/509448/84490528-41825880-acde-11ea-899b-dfabf420c658.png)

**Comment by misyobun** [comment]
@pvmodin

I realized your request in ver 1.1.0 .
if you want to hide labels and lines, as described below.

```
barChart.setOptions([.isHiddenExceptBars(true)])
```

You can try it!

From this version, the way which hide the label above bar is changed.

```
barChart.isHiddenLabelAboveBar = true
↓
barChart.setOptions([.isHiddenLabelAboveBar(true)])
```

**Comment by philmodin** [comment]
@misyobun This works great! Thank you.
