### ISSUE TITLE
Incorrect Bar Height or Incorrect Interval Label

### ISSUE THREAD

**Issue by philmodin** [misyobun/MSBBarChart#18]
Sometimes the bars are drawn at incorrect heights in relation to the interval lines when I set yAxisNumberOfInterval option.

If I don't set that option, then the charts draw correctly.

This one, I set .yAxisNumberOfInterval(4)
![image](https://user-images.githubusercontent.com/18331871/84710472-24859980-af19-11ea-88f1-31e435a62306.png)

This one, I set .yAxisNumberOfInterval(4)
![image](https://user-images.githubusercontent.com/18331871/84710490-29e2e400-af19-11ea-9de6-1a968052bd1d.png)

**Comment by misyobun** [comment]
I fixed it in my local code.
It's supposed to be like this when set .yAxisNumberOfInterval(4).

<img width="412" alt="スクリーンショット 2020-06-16 20 51 18" src="https://user-images.githubusercontent.com/509448/84770932-79a5d600-b013-11ea-9fc1-ecd1319cbe62.png">

**Comment by misyobun** [comment]
@pvmodin 
Thank you for your report!
I fixed this issue in Ver 1.1.2.
You can try it.

from this update, display of Each yAxisLabelValues has become Float type.

**Comment by philmodin** [comment]
@misyobun That fixed the issue, thanks!

We would like to use whole numbers for the y axis labels to allow maximum space for the chart bars. I would like to make the chart round up the max label value to a round number so all the interval lines would have round and easy to read numbers as pictured below. I'm learning how Github works and I'll see if I can do this and open a pr.

![IMG_8970](https://user-images.githubusercontent.com/18331871/84868700-f5af1680-b031-11ea-8968-3b167b5b8f61.jpg)
