### ISSUE TITLE
crash when chart data is empty

### ISSUE THREAD

**Issue by philmodin** [misyobun/MSBBarChart#20]
When there is no data passed to the chart it attempts to draw the view but CALayer crashes due to NaN in the yPosition

In version 1.1.1 this didn't crash. In version 1.1.2 it crashes.

Terminating app due to uncaught exception 'CALayerInvalidGeometry', reason:
'CALayer position contains NaN: [30.7857 nan].
Layer: <CALayer:0x281b12640;
position = CGPoint (30.7857 246);
bounds = CGRect (0 0; 45.5714 0);
allowsGroupOpacity = YES;
anchorPoint = CGPoint (0.5 1);
backgroundColor = <CGColor 0x283fba520> [<CGColorSpace 0x283fa4420> (kCGColorSpaceICCBased; kCGColorSpaceModelRGB; sRGB IEC61966-2.1; extended range)] ( 0.152941 0.658824 0.909804 1 );
animations = [bounds=<CABasicAnimation: 0x281b13d80>]>'

libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by misyobun** [comment]
@pvmodin 

As of now, I can't reproduce crash in my environment.

`When there is no data passed ` means following code？
```
self.barChart.setDataEntries(values: [])
```
or 
no call `setDataEntries(values: [value,value,value..])`

**Comment by philmodin** [comment]
@misyobun
Oh, good question.

setDataEntries(values: []) does not cause crash.

In my case it's:
setDataEntries(values: [0, 0, 0, 0, 0, 0, 0]) which causes crash.

**Comment by misyobun** [comment]
@pvmodin 
I see! 
I can reproduce it.
OK, I'll fix it.

**Comment by misyobun** [comment]
@pvmodin 
Thank you for your report!
I fixed this issue in Ver 1.1.3.
You can try it!

**Comment by philmodin** [comment]
@misyobun 
That fixed it. Thank you!
