### ISSUE TITLE
Scrolling clips content

### ISSUE THREAD

**Issue by philmodin** [misyobun/MSBBarChart#6]
With a large dataset, the chart enables scrolling but then clips the last bar when it settles.
Also the y axis interval lines don't cover the entire width of the view when scrolling is enabled.

![image](https://user-images.githubusercontent.com/18331871/84084638-ae24ec80-a998-11ea-941d-9e4574abcb37.png)

^ pulling the view reveals the last bar 31 ^

![image](https://user-images.githubusercontent.com/18331871/84084704-d14f9c00-a998-11ea-9c80-dfc57aa5ee71.png)

^ letting go settles the view and clips bar 30 and 31 ^

![image](https://user-images.githubusercontent.com/18331871/84085386-55eeea00-a99a-11ea-87e5-a31952938f4f.png)

^ bar 1 and 13 are visible but the axis and interval lines don't extend that far ^

**Comment by misyobun** [comment]
Hi! @pvmodin 
Thanks for your issue.
In ver 1.0.4, this problem was fixed.
(https://github.com/misyobun/MSBBarChart/pull/7#issuecomment-640991335)
You can check it out.

**Comment by philmodin** [comment]
@misyobun Very quick, thank you!

1. Noticed that now it will be scrollable even when it doesn't need to
![alwaysscroll](https://user-images.githubusercontent.com/18331871/84133289-d72a9900-a9fb-11ea-88dc-17171d71ae00.gif)

2. When there's just one bar, it makes extra space for another bar.
![extra space](https://user-images.githubusercontent.com/18331871/84133142-a64a6400-a9fb-11ea-9e95-74fa8bf21d09.gif)

3. When I set .setOptions([.space(2)]) or less it clips the last bar.
![clips](https://user-images.githubusercontent.com/18331871/84133834-836c7f80-a9fc-11ea-9083-2325f00729bd.gif)

**Comment by misyobun** [comment]
@pvmodin 
oh.. I blew it..
Thank you for confirming.
I fixed it in ver 1.0.5, so you can try it.

**Comment by philmodin** [comment]
@misyobun Almost perfect.

When the spacing is less than 8 and scrolling is off, it clips the last bar.
![IMG_8616](https://user-images.githubusercontent.com/18331871/84209293-ac2b5e00-aa6a-11ea-983a-c37c4dd2abfc.jpg)

**Comment by misyobun** [comment]
@pvmodin 
thanks for your checking.
I fixed it in ver 1.0.6, so you can try it.

## After (ver 1.0.6)
![スクリーンショット 2020-06-10 10 56 46](https://user-images.githubusercontent.com/509448/84218653-d1bb7480-ab09-11ea-9765-53cc4b7e5a4e.png)

**Comment by philmodin** [comment]
@misyobun It works! 😁 Thank you!
